### ISSUE TITLE
Build PCB(s)

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPi#2]
Get a new circuit boards built and tested and installed into TWIPi.

**Comment by nerdoug** [comment]
To Do's:
-decide on board orientation and position
-decide which side of MB the IBC connector should be mounted
    -may require MB notch to allow IBC cable to reach PB
-decide how we implement card cage "rails"
    -slots cut into existing pieces on all 4 sides, or 3 sides
    -built up edge holders as part of 4 vertical panels, on 3 or 4 sides
    -4 sides approach lets boards come out through any side
-get PB1A and PB1B layouts done, with associated ICB pinout changes
