### ISSUE TITLE
Use inter-board connectors other than 25pin SUB-D

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPi#34]
Pick new "daughter board" connection parts. Likely copy what Arduino boards use to connect daughter boards. Think of using different numbers of pins arrange asymmetrically so that there is only one way to mate the two boards.

**Comment by nerdoug** [comment]
This is completed in the single board version (SB3) we're now using. It uses a smaller, keyed connector to connect to the switches, USB jack and LEDs that are externally accessible.
