### ISSUE TITLE
Investigate industry standard trace width

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPi#37]
Figure out what size traces we should use on our boards. This goes hand in hand with figuring out how to use Fusion to create boards rather than rely on FlatCAM.

**Comment by nerdoug** [comment]
Used 2 online tools to evaluate trace with needed for the heavy-duty traces, the ones that carry motor current, both 12V and ground. The tools and parameters are shown in the 2nd and 3rd sheets of the cad-conversions.ods spreadsheet. Net result is that we need 50 mil wide traces for these paths.

For other traces, I used the following parameters in the ninja tool:
.5 Amp current
20 degree C temperature rise
1.6 mm board thickness
32 um track thickness
no plane present
0.2 thermal conductivity

and got a minimal Track width of 2.1 mils or 0.053 mm. We're now using 16 mil track width, so we have lots of safety margin.
