### ISSUE TITLE
Create shopping list of parts

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPi#6]
Need to get a list of parts to stuff the PCB boards that we are making.

**Comment by va3wam** [comment]
See issues 7 and 10 for details needed to purchase the correct motors. Also see task 11 regarding purchasing the items from this list.

**Comment by nerdoug** [comment]
initial parts list uploaded to /.../EagleCAD/doc . More details and part numbers needed, and the results of some ongoing investigations.
